<center> <h1>QuACK workshop: Linear Algebra</h1> </center>

## Thursday, October 13, 2016

## Outline
   * Why linear algebra?
   * Basics of linear algebra: worksheet
   * Linear regression example
   * Some more examples to check out and resources 
   

**Linear algebra might look like what you’ve seen, but there are some important differences!**


### Basics:
* Vectors
* Matrices
* Dot products
* Matrix dimensions
* Matrix operations
* Transpose of a matrix
* Eigenvectors and eigenvalues

$1.$	What is a vector? An example or a drawing will suffice.

$2.$	Please give an example of a matrix. What are they used for?

$$\begin{bmatrix}
    x_{11}       & x_{12} & x_{13} & \dots & x_{1n} \\
    x_{21}       & x_{22} & x_{23} & \dots & x_{2n} \\
    x_{d1}       & x_{d2} & x_{d3} & \dots & x_{dn}
\end{bmatrix}$$

$3.$ 	Let $v$ be the vector $(2,5,7)$. What is $3 ∙ v$ ?

In [1]:
v = c(2,5,7)
v
3*v

[1] 2 5 7

[1]  6 15 21

$4.$ Let $w$ be the vector $(3,4,1)$. What is the dot product $v ∙w$ ?

In [2]:
w = c(3,4,1)
w
v %*% w

[1] 3 4 1

[,1]
[1,] 33

$5.$	If you multiply a 2 x 3 matrix with a 3 x 7 matrix, what is the size of the matrix you will end up with? What about if you multiply a 4 x 4 with a 3 x 4? 

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13}\\ a_{21} & a_{22} & a_{23}\end{bmatrix} \cdot \begin{bmatrix} b_{11} & b_{12} & b_{13} & b_{14} & b_{15} & b_{16} & b_{17} \\ b_{21} & b_{22} & b_{23} & b_{24} & b_{25} & b_{26} & b_{27}\\ b_{31} & b_{32} & b_{33} & b_{34} & b_{35} & b_{36} & b_{37} \\  \end{bmatrix} =  ?
$$

$$
\begin{bmatrix} x_{11} & x_{12} & x_{13} & x_{14}\\ x_{21} & x_{22} & x_{23} & x_{24} \\ x_{31} & x_{32} & x_{33} & x_{34} \\ x_{41} & x_{42} & x_{43} & x_{44}\end{bmatrix} \cdot \begin{bmatrix} y_{11} & y_{12} & y_{13} & y_{14}\\ y_{21} & y_{22} & y_{23} & y_{24}\\ y_{31} & y_{32} & y_{33} & y_{34} \end{bmatrix} =  ?
$$

In [3]:
M1 = matrix(rnorm(6),2,3) # generates 6 numbers from a normal distribution and arranges them in a 2x3 matrix
M2 = matrix(rnorm(21),3,7) 
dim(M1)
dim(M2)
dim(M1 %*% M2)

[1] 2 3

[1] 3 7

[1] 2 7

In [4]:
M1 = matrix(rnorm(16),4,4)  
M2 = matrix(rnorm(12),3,4)  
dim(M1)
dim(M2)
dim(M1 %*% M2) # you should get an error!

[1] 4 4

[1] 3 4

ERROR: Error in M1 %*% M2: non-conformable arguments


$6.$ Let $A$ and $B$ be matrices:  
$$A = \begin{bmatrix}
    2 & 1 \\
    5 & 0 \\
\end{bmatrix}$$

$$B = \begin{bmatrix}
    1 & 1 \\
    4 & 2 \\
\end{bmatrix}$$
Calculate $A + B$, $AB$, and $2A – B$.

In [9]:
A = matrix(c(2,5,1,0),nrow=2,ncol=2)
B = matrix(c(1,1,4,2),nrow=2,ncol=2,byrow=T)
A
B

[,1] [,2]
[1,] 2    1   
[2,] 5    0

[,1] [,2]
[1,] 1    1   
[2,] 4    2

In [10]:
dim(A)
dim(B)

[1] 2 2

[1] 2 2

$$
A + B = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} + \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} a_{11} + b_{11} & a_{12} + b_{12} \\ a_{21} + b_{21} & a_{22} + b_{22} \end{bmatrix}
$$

In [11]:
A+B

[,1] [,2]
[1,] 3    2   
[2,] 9    2

$$
A \cdot B = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} \cdot \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} a_{11} \cdot b_{11} + a_{12} \cdot b_{21} & a_{11} \cdot b_{12} + a_{12} \cdot b_{22} \\ a_{21} \cdot b_{11} + a_{22} \cdot b_{21} & a_{21} \cdot b_{12} + a_{22} \cdot b_{22} \end{bmatrix}
$$

In [12]:
A*B # careful, this does element-wise multiplication! 

[,1] [,2]
[1,]  2   1   
[2,] 20   0

In [18]:
A %*% B # this is the appropriate operation in R for matrix multiplication!

[,1] [,2]
[1,] 6    4   
[2,] 5    5

$$
2 \cdot A - B = 2 \cdot \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} - \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} 2 \cdot a_{11} - b_{11} & 2\cdot a_{12} - b_{12} \\ 2 \cdot a_{21} - b_{21} & 2\cdot a_{22} - b_{22} \end{bmatrix}
$$

In [20]:
2 * A - B

[,1] [,2]
[1,] 3     1  
[2,] 6    -2

$7.$ What is the norm of the vector $(3,1,2,4)$?

In [57]:
x  <- c(3,1,2,4)
length(x) # careful, this just tells you how many elements are in a vector!

[1] 4

We want to calculate: $||x|| = \sqrt{x_1^2 + x_2^2 + ... + x_n^2} = \sqrt{x \cdot x}$

In [64]:
norm(x, type="2") # this gives the euclidean norm
sqrt(sum(x*x)) # this is the mathematical version

[1] 5.477226

[1] 5.477226

$8.$ What is a unit vector? 

In [69]:
unitx <- x/(norm(x, type="2"))
norm(unitx, type="2") # this show us that x is of length 1! The definition of a unit vector

[1] 1

$9.$ What is the transpose of $B$?

$$
\begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}^T = \begin{bmatrix} a_{11} & a_{21} \\ a_{12} & a_{22} \end{bmatrix}
$$

In [ ]:
t(B)

$10.$ What is an eigenvector? An eigenvalue? 


$$
\begin{align}
\textbf{A} &\cdot \textbf{x} &= \lambda &\cdot \textbf{x} \\
\begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} &\cdot \left[ \begin{array}{c} x_1 \\ x_2 \end{array} \right] &= \lambda &\cdot \left[  \begin{array}{c} x_1 \\ x_2 \end{array} \right]
\end{align}
$$

$\textbf{x} =\left[ \begin{array}{c} x_1 \\ x_2 \end{array} \right]$ is an **eigenvector** of the matrix $\textbf{A}$.

$\lambda$ is the **eigenvalue** of the matrix $\textbf{A}$, corresponding to the eigenvector $\textbf{x}$.

In [3]:
M = matrix(c(4,-1,2,1),nrow=2,ncol=2) 
M
eigen(M)

[,1] [,2]
[1,]  4   2   
[2,] -1   1

$values
[1] 3 2

$vectors
           [,1]       [,2]
[1,]  0.8944272 -0.7071068
[2,] -0.4472136  0.7071068


---
## Defining Matrices in R


In [1]:
M = matrix(c(2, 4, 3, 1, 5, 7),nrow=3,ncol=2) 
M

t(M) # transpose of B

[,1] [,2]
[1,] 2    1   
[2,] 4    5   
[3,] 3    7

[,1] [,2] [,3]
[1,] 2    4    3   
[2,] 1    5    7

In [11]:
W <- matrix(c(rep(1, 3), rep(2, 3)), 2, byrow = T)
W
X <- matrix(c(3, 3, 3), nrow=3, ncol=1)
X
Y <- rbind(W,t(X))
Y
Z <- cbind(t(W),X)
Z

c(Z) # deconstructs the matrix

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 2    2    2

[,1]
[1,] 3   
[2,] 3   
[3,] 3

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 2    2    2   
[3,] 3    3    3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 1    2    3   
[3,] 1    2    3

[1] 1 1 1 2 2 2 3 3 3

# Uses of inner product


$$
x \cdot y = x^T \cdot y
$$

### Cosine computed with inner products:
$$
cos(x,y) = \frac{x^T \cdot y}{||x|| \cdot ||y||}
$$
where $||x|| = \sqrt{x_1^2 + x_2^2 + ... + x_n^2} = \sqrt{x \cdot x}$ is the norm of vector $x$.

This is a normalized inner product, since we're dividing by the norm of $x$ and of $y$.



In [28]:
#plot(c(0,1),c(0,1))
#arrows(0,0,1,1,col = "red") # can use this to plot vectors

In [95]:
x <-  c(1,0)
y <-  c(-1,0)
normx <- norm(x, type="2")
normy <- norm(y, type="2")
cospi <- cos(pi)
cosxy <- (x%*%y)/(normx*normy)
sprintf("cos(pi): %s", cospi)
sprintf("cos(x,y): %s", cosxy)

[1] "cos(pi): -1"

[1] "cos(x,y): -1"


---
# Resources:
* https://www.khanacademy.org/math/linear-algebra